### ISSUE TITLE
[META] Reorganize issues / projects / wikis

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/elvis#553]
@jfacorro / @paulo-ferraz-oliveira : What do you think about…

- [x] Copying the elvis-core issues to the `elvis_core` repo?
- [x] Removing the wiki from this project? Or, at least, leaving just a link to the one in `elvis_core`?

**Comment by paulo-ferraz-oliveira** [comment]
I'm OK with both.

**Comment by paulo-ferraz-oliveira** [comment]
Is there an easy way to copy between repo.s?
Also, when updating/removing the Wiki we should make sure the appropriate info. makes its way to `README.md`.

**Comment by elbrujohalcon** [comment]
I'm not sure if there is an easy way… My plan was to do it _The Hard Way_:tm:

**Comment by elbrujohalcon** [comment]
- [ ] Activate github discussions?

**Comment by paulo-ferraz-oliveira** [comment]
I'm OK with Discussions and making this the first discussion 😄

**Comment by paulo-ferraz-oliveira** [comment]
- [ ] make sure the content of https://github.com/inaka/elvis/wiki is in the README
- [ ] make sure the content of https://github.com/inaka/elvis/wiki/Benefits-&-Roadmap is in the README [1] [2]
- [ ] make sure https://github.com/inaka/elvis/wiki/Default-Rules-in-Elvis-Webhook is ported to `elvis_core` [3] [4]
- [ ] make sure https://github.com/inaka/elvis/wiki/Introduction-&-Features is ported to README [5]
- [ ] kill https://github.com/inaka/elvis/wiki/Rules

(_I wonder how difficult it would be to make `elvis` into a GitHub Action_)

---

[1] I didn't "port" `- Implement more rules that enforce additional Erlang guidelines.` since this is a constant work in progress.
[2] I'll port the Benefits to `README.md`: e0aeda4
[3] I left Rules out, since this is basically part of `elvis_core`
[4] I left Customization out, since I believe it's not important as-is
[5] I'll include this in the same pull request as [2]: 4c56984

**Comment by paulo-ferraz-oliveira** [comment]
It should be possible to [transfer an open issue to another repository](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/transferring-an-issue-to-another-repository#transferring-an-open-issue-to-another-repository), but I don't think I have permissions for it, so leave it up to you guys.

**Comment by elbrujohalcon** [comment]
Yeah… My plan is to work on the movement of tickets and stuff at some point during my vacations. That is… in 2 weeks.

**Comment by paulo-ferraz-oliveira** [comment]
What else could I do to help here?

**Comment by elbrujohalcon** [comment]
> What else could I do to help here?

Wait... I guess 😜

**Comment by elbrujohalcon** [comment]
Done.

**Comment by paulo-ferraz-oliveira** [comment]
El hombre.
